/* ==========================================================================
   Aura Canvas — In-Browser Brainstorming Agent Engine
   ========================================================================== */

export class BrainstormingAgent {
  constructor(nodeManager, canvasEngine) {
    this.nodeManager = nodeManager;
    this.canvasEngine = canvasEngine;

    // Knowledge Bank for instant intelligent node expansions
    this.knowledgeBank = {
      'ai': ['LLM RAG Engine', 'Vector Embeddings DB', 'Prompt Templates', 'Model Fine-tuning', 'Safety Guardrails'],
      'design': ['UI Design System', 'Color Palette & Contrast', 'Typography Hierarchy', 'Micro-animations', 'User Journey Map'],
      'launch': ['Landing Page Copy', 'Beta User Outreach', 'Product Hunt Post', 'Analytics Tracking', 'Customer Feedback Form'],
      'dev': ['API Gateway Routing', 'Database Schema Design', 'CI/CD Pipeline', 'Unit & E2E Testing', 'Performance Audit'],
      'marketing': ['Social Media Campaign', 'SEO Optimization', 'Email Newsletter', 'Influencer Partnerships', 'Ad Copy A/B Test']
    };
  }

  // 1. Expand a single node into a cluster of related ideas
  expandNode(sourceNodeId) {
    const sourceNode = this.nodeManager.nodes.find(n => n.id === sourceNodeId);
    if (!sourceNode) return [];

    const topic = sourceNode.title.toLowerCase();
    let suggestions = ['Core Requirements', 'Risk Analysis', 'User Experience Flow', 'Technical Feasibility'];

    // Match keywords from title
    for (const key in this.knowledgeBank) {
      if (topic.includes(key)) {
        suggestions = this.knowledgeBank[key];
        break;
      }
    }

    const createdNodes = [];
    const radius = 240;
    const count = Math.min(4, suggestions.length);

    for (let i = 0; i < count; i++) {
      const angle = (i / count) * (Math.PI * 1.5) - (Math.PI / 4);
      const targetX = Math.round(sourceNode.x + Math.cos(angle) * radius + (Math.random() * 40 - 20));
      const targetY = Math.round(sourceNode.y + Math.sin(angle) * radius + (Math.random() * 40 - 20));

      const colors = ['cyan', 'purple', 'pink', 'amber', 'emerald'];
      const newNode = this.nodeManager.addNode('note', targetX, targetY, {
        title: suggestions[i],
        content: `Brainstormed sub-topic connected to "${sourceNode.title}".`,
        color: colors[i % colors.length],
        status: 'Ideas',
        tags: ['#ai-brainstorm']
      });

      // Automatically create connection
      const handles = ['right', 'bottom', 'left', 'top'];
      this.nodeManager.addConnection(
        sourceNode.id, handles[i % 4],
        newNode.id, handles[(i + 2) % 4],
        'expands into'
      );

      createdNodes.push(newNode);
    }

    return createdNodes;
  }

  // 2. Generate a full Mind Map Node Tree from a prompt
  generateMindMap(topicName) {
    const centerScreen = this.canvasEngine.screenToWorld(window.innerWidth / 2, window.innerHeight / 2);
    const rootX = Math.round(centerScreen.x - 140);
    const rootY = Math.round(centerScreen.y - 80);

    // Create Root Concept Node
    const rootNode = this.nodeManager.addNode('note', rootX, rootY, {
      title: `🎯 ${topicName.toUpperCase()}`,
      content: `Central topic map generated by Brainstorming Agent.`,
      color: 'purple',
      status: 'In Progress',
      width: 280,
      height: 150
    });

    // Sub-branches based on topic
    const subTopics = [
      { title: '1. Vision & Strategy', color: 'cyan', tasks: ['Define Target Audience', 'Set KPI Goals', 'Competitor Benchmark'] },
      { title: '2. Product Features', color: 'emerald', tasks: ['Core UX Flows', 'Interactive Prototype', 'Feedback Loop'] },
      { title: '3. Technical Stack', color: 'pink', tasks: ['Frontend Framework', 'Backend Services', 'Data Storage'] },
      { title: '4. Go-To-Market', color: 'amber', tasks: ['Landing Page', 'Launch Announcement', 'Community Hub'] }
    ];

    const radius = 320;
    subTopics.forEach((sub, idx) => {
      const angle = (idx / subTopics.length) * (2 * Math.PI) - (Math.PI / 2);
      const branchX = Math.round(rootX + Math.cos(angle) * radius);
      const branchY = Math.round(rootY + Math.sin(angle) * radius);

      const branchNode = this.nodeManager.addNode('task', branchX, branchY, {
        title: sub.title,
        color: sub.color,
        status: 'To Do',
        tasks: sub.tasks.map(t => ({ text: t, completed: false }))
      });

      // Connect root to branch
      const handles = ['top', 'right', 'bottom', 'left'];
      this.nodeManager.addConnection(
        rootNode.id, handles[idx],
        branchNode.id, handles[(idx + 2) % 4],
        'branch'
      );
    });

    // Wrap in a frame
    this.nodeManager.addFrame(rootX - 420, rootY - 420, 1120, 880, `Brainstorm Map: ${topicName}`);
    this.canvasEngine.zoomFit();
    return rootNode;
  }

  // 3. Convert any note into a structured task breakdown
  convertNoteToTasks(sourceNodeId) {
    const node = this.nodeManager.nodes.find(n => n.id === sourceNodeId);
    if (!node) return;

    const taskItems = [
      { text: `Research specifications for ${node.title}`, completed: false },
      { text: `Draft initial prototype & mockups`, completed: false },
      { text: `Review with team & collect feedback`, completed: false },
      { text: `Finalize implementation`, completed: false }
    ];

    this.nodeManager.updateNode(sourceNodeId, {
      type: 'task',
      tasks: taskItems
    });
  }

  // 4. Auto-connect orphan nodes on canvas
  autoConnectOrphans() {
    const nodes = this.nodeManager.nodes;
    if (nodes.length < 2) return 0;

    let connectedCount = 0;
    nodes.forEach((nodeA, i) => {
      // Find closest node that isn't connected to nodeA
      let closestNode = null;
      let minDistance = Infinity;

      nodes.forEach((nodeB, j) => {
        if (i === j) return;
        const isConnected = this.nodeManager.connections.some(c => 
          (c.fromNodeId === nodeA.id && c.toNodeId === nodeB.id) ||
          (c.fromNodeId === nodeB.id && c.toNodeId === nodeA.id)
        );

        if (!isConnected) {
          const dist = Math.hypot(nodeA.x - nodeB.x, nodeA.y - nodeB.y);
          if (dist < minDistance && dist < 500) {
            minDistance = dist;
            closestNode = nodeB;
          }
        }
      });

      if (closestNode) {
        this.nodeManager.addConnection(nodeA.id, 'right', closestNode.id, 'left', 'relates to');
        connectedCount++;
      }
    });

    return connectedCount;
  }
}
